<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ejercicio calculadora PHP</title>
</head>
<body>


      <form  method = "post" action="calcuPost.php">
        
        
        Ingresar el primer numero<input type="Text" name="num1"></br>
        Ingresa el segundo numero<input type="Text" name="num2"></br>
        
        <br>
        <input type="submit" value="Sumar" name ="sum ">
        <input type="submit" value="Restar" name ="res ">
        <input type="submit" value="Multiplicar"name ="mul ">
        <input type="submit" value="Dividir"name ="div ">
      </form>    

</body>
</html>